name: PureChat
main: _64FF00\PureChat\PureChat
version: "1.4.0-BETA-02"
api: [1.13.0, 2.0.0]
load: POSTWORLD
author: 64FF00
website: https://github.com/PurePlugins/PureChat
depend: [PurePerms]
softdepend: [FactionsPro, XeviousPE-Factions]
commands:
  setprefix:
    description: "Allows you to set your PureChat prefix"
    permission: pchat.command.setprefix
  setsuffix:
    description: "Allows you to set your PureChat suffix"
    permission: pchat.command.setsuffix	
permissions:
  pchat:
    description: "PureChat by 64FF00! (Twitter: @64FF00)"
    children:
      pchat.command:
        description: "Allows you to use all PureChat commands."
        children:
          pchat.command.setprefix:		
            description: "Allows you to set your PureChat prefix"
          pchat.command.setsuffix:		
            description: "Allows you to set your PureChat suffix"			
      pchat.coloredMessages:
        description: "Allows you to use colors in chat"		